import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF3E0",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    alignItems: "center",
  },
  header: {
    backgroundColor: "#FFA726",
    flexDirection: "row",
    borderColor: "#DD6E42",
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    backgroundColor: "#FFA726",
    flexDirection: "row",
    borderColor: "#DD6E42",
    borderWidth: 2,
    fontFamily: "Comfortaa-Bold",
  },
  title: {
    color: "#FFF3E0",
    fontWeight: "bold",
    flex: 1,
    fontSize: 23,
    textAlign: "center",
    margin: 10,
    fontFamily: "Comfortaa-Bold",
  },
  author: {
    color: "#5D4037",
    fontWeight: "bold",
    flex: 1,
    fontSize: 15,
    textAlign: "center",
    margin: 10,
    fontFamily: "Comfortaa-Light",
  },
  gameboard: {
    backgroundColor: "#FFF3E0",
    alignItems: "center",
    justifyContent: "center",
  },
  gameinfo: {
    color: "#5D4037",
    fontSize: 16,
    lineHeight: 20,
    textAlign: "justify",
    marginHorizontal: 20,
    backgroundColor: "#FFF3E0",
    padding: 10,
    borderRadius: 5,
    fontFamily: "Comfortaa-Regular",
  },

  noScores: {
    color: "#5D4037",
    fontSize: 16,
    lineHeight: 20,
    textAlign: "justify",
    marginHorizontal: 20,
    backgroundColor: "#FFF3E0",
    padding: 10,
    borderRadius: 5,
    marginBottom: 403,
    fontFamily: "Comfortaa-Regular",
  },
  rulesTitle: {
    color: "#FF6F00",
    fontSize: 20,
    // fontWeight: "bold",
    marginVertical: 10,
    textAlign: "center",
    marginTop: 20,
    fontFamily: "Comfortaa-Bold",
  },
  row: {
    marginTop: 20,
    padding: 10,
    borderColor: "#FFB74D",
    borderWidth: 1,
    fontFamily: "Comfortaa-Regular",
  },
  flex: {
    flexDirection: "row",
  },
  button: {
    marginTop: 15,
    marginBottom: 30,
    alignSelf: "center",
    paddingVertical: 8,
    paddingHorizontal: 20,
    backgroundColor: "#FB8C00",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#EF6C00",
    borderWidth: 2,
    fontFamily: "Comfortaa-Regular",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 18,
    //fontWeight: "bold",
    fontFamily: "Comfortaa-Regular",
  },
  textInput: {
    height: 40,
    marginTop: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#FFB74D",
    backgroundColor: "#FFF3E0",
    color: "#FF6F00",
    padding: 10,
    borderRadius: 5,
    fontSize: 16,
    //fontWeight: "500",
    textAlign: "center",
    fontFamily: "Comfortaa-Regular",
  },
  staticDicesTopContainer: {
    justifyContent: "center",
    marginTop: 220,
    marginLeft: -100,
    marginBottom: -80,
  },
  gameDices: {
    marginHorizontal: -10,
    marginBottom: 25,
    marginTop: 25,
  },
  head: {
    height: 40,
    backgroundColor: "#f1f8ff",
    fontFamily: "Comfortaa-Regular",
  },
  text: {
    textAlign: "center",
    //fontWeight: "200",
    fontFamily: "Comfortaa-Regular",
  },
  row: {
    height: 28,
    backgroundColor: "#E7E6E1",
    fontFamily: "Comfortaa-Regular",
  },

  cardContainer: {
    padding: 0,
    margin: 0,
    borderWidth: 0,
    fontFamily: "Comfortaa-Regular",
  },
  scoreRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    fontFamily: "Comfortaa-Regular",
    borderBottomWidth: 1,
    borderBottomColor: "gray",
  },
  cell: {
    fontSize: 18,
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    backgroundColor: "lightgray",
    fontFamily: "Comfortaa-Regular",
  },
  headerCell: {
    fontSize: 18,
    //fontWeight: "bold",
    flex: 1,
    fontFamily: "Comfortaa-Bold",
  },
  scoreHeaderCell: {
    fontSize: 18,
    //fontWeight: "bold",
    flex: 1,
    textAlign: "right",
    fontFamily: "Comfortaa-Regular",
  },

  //Modal
  fullScreenCentered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)", // Semi-transparent background
  },

  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonClose: {
    backgroundColor: "#2196F3",
    width: 150,
    height: 50,
    paddingVertical: 10,
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    elevation: 2,
    marginTop: 15,
    borderColor: "#EF6C00",
    borderWidth: 2,
  },

  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    textAlign: "center",
  },
});
